apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5005
          env:
            - name: PORT
              value: "5005"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI_PAYMENT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STRIPE_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: healthcare
spec:
  selector:
    app: payment-service
  ports:
    - port: 5005
      targetPort: 5005
  type: ClusterIP
