apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: healthcare
type: Opaque
data:
  JWT_SECRET: MjZmOWQxMjM1NTVkYjQ2OTQyNzZkZTYzZTVmYzFlYmI=
  MONGO_URI_AUTH: bW9uZ29kYitzcnY6Ly9pdDIzMjk3NzIyX2RiX3VzZXI6TGhzdEcwN2tCOHRhU3pZUkBjbHVzdGVyMC5ubmVmcGg1Lm1vbmdvZGIubmV0Lw==
  MONGO_URI_PATIENT: bW9uZ29kYitzcnY6Ly9DaGF0aHVtaTpZM1MyMjAyNkBjbHVzdGVyMC5ubmVmcGg1Lm1vbmdvZGIubmV0L3BhdGllbnRfZGI/YXBwTmFtZT1DbHVzdGVyMA==
  MONGO_URI_DOCTOR: bW9uZ29kYitzcnY6Ly9pdDIzMjk3NzIyX2RiX3VzZXI6TGhzdEcwN2tCOHRhU3pZUkBjbHVzdGVyMC5ubmVmcGg1Lm1vbmdvZGIubmV0L2RvY3RvcnNfZGI/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
  MONGO_URI_APPOINTMENT: bW9uZ29kYitzcnY6Ly9pdDIzMjk3NzIyX2RiX3VzZXI6TGhzdEcwN2tCOHRhU3pZUkBjbHVzdGVyMC5ubmVmcGg1Lm1vbmdvZGIubmV0L2FwcG9pbnRtZW50c19kYj9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  MONGO_URI_TELEMEDICINE: bW9uZ29kYitzcnY6Ly9EaW51cmk6V2RCdmJxRUU0YzhCY3BGYkBjbHVzdGVyMC5ubmVmcGg1Lm1vbmdvZGIubmV0L3RlbGVtZWRpY2luZV9kYg==
  MONGO_URI_PAYMENT: bW9uZ29kYitzcnY6Ly9EaW51cmk6V2RCdmJxRUU0YzhCY3BGYkBjbHVzdGVyMC5ubmVmcGg1Lm1vbmdvZGIubmV0L3BheW1lbnRfZGI=
  CLOUDINARY_API_KEY: OTQyMjIyNTg4Mjk0ODI4
  CLOUDINARY_API_SECRET: SW5FaE9tSVZkZHQ3cTBZRWNORVlEeXVQY293
  STRIPE_SECRET: c2tfdGVzdF81MVRHTWhsR2N5cms2cjdQNlIwRzRWbkxJdnVnVm14VVZvOE5wRktmQlhWcEVGV0pxa2tQV3ZuQkFPV1lhWWhGSFRObFd6VlpMMEtRNW1aemQxOUZKWnBCSjAwT1d6Sk42Zms=
  EMAIL_PASS: a2d3bSBna2pkIHZveWYgcm9lbw==
  NOTIFY_API_KEY: S0NCZ2N6VTI5TUFGR01HbmVmdUM=
