apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: healthcare
type: Opaque
data:
  JWT_SECRET: MjZmOWQxMjM1NTVkYjQ2OTQyNzZkZTYzZTVmYzFlYmI=
  MONGO_URI_AUTH: <base64>
  MONGO_URI_PATIENT: bW9uZ29kYitzcnY6Ly9DaGF0aHVtaTpZM1MyMjAyNkBjbHVzdGVyMC5ubmVmcGg1Lm1vbmdvZGIubmV0L3BhdGllbnRfZGI/YXBwTmFtZT1DbHVzdGVyMA==
  MONGO_URI_DOCTOR: <base64>
  MONGO_URI_APPOINTMENT: <base64>
  MONGO_URI_TELEMEDICINE: <base64>
  MONGO_URI_PAYMENT: <base64>
  CLOUDINARY_API_KEY: OTQyMjIyNTg4Mjk0ODI4
  CLOUDINARY_API_SECRET: SW5FaE9tSVZkZHQ3cTBZRWNORVlEeXVQY293
  STRIPE_SECRET: <base64>
  EMAIL_PASS: a2d3bSBna2pkIHZveWYgcm9lbw==
  NOTIFY_API_KEY: S0NCZ2N6VTI5TUFGR01HbmVmdUM=
