apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: telemedicine-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI_TELEMEDICINE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
  namespace: healthcare
spec:
  selector:
    app: telemedicine-service
  ports:
    - port: 5004
      targetPort: 5004
  type: ClusterIP
